#!/usr/bin/env python

import sys
import sherd

try:
    source_dir, output_dir, mirrorfile = sys.argv[1:]
except ValueError:
    print """Usage: 
%s <input dir> <output dir> <mirror file>
"""
    sys.exit(1)
mirrors = []
with open(mirrorfile) as fh:
    for line in fh:
        mirrors.append(line.strip())
sherd.Generator(source_dir, output_dir, mirrors).generate_site()

